name: mobile_app
description: "A lightweight weight loss assistant."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.11.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  http: ^1.2.2
  provider: ^6.1.2
  fl_chart: ^1.1.1
  google_fonts: ^6.2.1
  flutter_animate: ^4.5.2
  font_awesome_flutter: ^10.7.0
  animations: ^2.0.11
  intl: ^0.19.0
  flutter_markdown: ^0.7.7+1
  image_picker: ^1.2.1
  shared_preferences: ^2.5.4
  uuid: ^4.5.1
  cached_network_image: ^3.4.1 # 优化网络图片加载与缓存

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/app_icon.svg"
  min_sdk_android: 21 # android min sdk min:16, default:21

flutter:
  uses-material-design: true
  assets:
    - assets/icon/
